### ISSUE TITLE
 Login to Odoo 10 (community version) -> java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference

### ISSUE THREAD

**Issue by donghd** [Odoo-mobile/framework#245]
@dpr-odoo 
There is exception when login to Odoo 10 (community version), are there any help?
(Even got latest version from Github)
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.erpviet, PID: 24285
                  java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                      at odoo.wrapper.OdooWrapper.onResponse(OdooWrapper.java:1213)
                      at odoo.wrapper.OdooWrapper.onResponse(OdooWrapper.java:68)
                      at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
                      at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:145)
                      at android.app.ActivityThread.main(ActivityThread.java:6837)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

Log in server side:
ERROR ? odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "XXX/odoo_10.0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "XXX/odoo_10.0/odoo/http.py", line 1443, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/Library/Python/2.7/site-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found

**Comment by darfat** [comment]
hi @donghd i have same problem, that error cause from this code

`if(this.mVersion.getVersionNumber() > 7) {
            this.odooSession.setCompanyId(response.getInt("company_id"));
        }`

the response didnt get company_id property.
the temporary solution what i is : 
on the `/web/session/authenticate` method on server (main.py) then add `company_id` property on `session_info `method 

`def session_info(self):

        request.session.ensure_valid()

        return {

            "session_id": request.session_id,

            "uid": request.session.uid,

            "user_context": request.session.get_context() if request.session.uid else {},

            "db": request.session.db,

            "username": request.session.login,

            "company_id" : 1
`

**Comment by donghd** [comment]
hi @darfat , @dpr-odoo
I am not sure , but I may think, client (mobile) must be able to handle such kind of return value from server side(whatsoever). Besides, exception when response's id=null (not company_id), please check below for detail:
As my investigate:
-----------------------
◆odoo-rpc-v3's OdooWrapper.class, below callback onResponse 2 time right after input url-self host when login on mobile:
public void onResponse(JSONObject response) {
    ...
        OdooResponse responseMap = this.parseToResponse(response);
        if(responseMap != null) {
            int id = responseMap.id.intValue();  ← Exception happened 
       .....
◆The 2nd time, it cause trouble, please refer below to see data that is parsing (parseToResponse) incorrectly that .
response={"jsonrpc":"2.0","id":677,"error":{"message":"Odoo Server Error","code":200,"data":{"debug":"Traceback (most recent call last):\n  File \"\/opt\/odoo_v10\/odoo\/http.py\", line 638, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"\/opt\/odoo_v10\/odoo\/addons\/base\/ir\/ir_http.py\", line 177, in _dispatch\n    rule, arguments = cls._find_handler(return_rule=True)\n  File \"\/opt\/odoo_v10\/odoo\/addons\/base\/ir\/ir_http.py\", line 79, in _find_handler\n    return cls.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)\n  File \"\/root\/.local\/lib\/python2.7\/site-packages\/werkzeug\/routing.py\", line 1430, in match\n    raise NotFound()\nNotFound: 404: Not Found\n","exception_type":"internal_error","message":"","name":"werkzeug.exceptions.NotFound","arguments":[]}}}

responseMap=OdooResponse{jsonrpc='null', error='null', id=null, result={error={message=Odoo Server Error, code=200.0, data={debug=Traceback (most recent call last):
  File "/opt/odoo_v10/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo_v10/odoo/addons/base/ir/ir_http.py", line 177, in _dispatch
    rule, arguments = cls._find_handler(return_rule=True)
  File "/opt/odoo_v10/odoo/addons/base/ir/ir_http.py", line 79, in _find_handler
    return cls.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/root/.local/lib/python2.7/site-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found
, exception_type=internal_error, message=, name=werkzeug.exceptions.NotFound, arguments=[]}}, id=677.0, jsonrpc=2.0}}

id should be = 677 (not null)???
---------------------
Because have no source code of odoo-rpc-v3, so we cannot handle this kind of error ....:(

**Comment by dpr-odoo** [comment]
Fixed for Odoo 10.0 Database getting crash. https://github.com/Odoo-mobile/framework/commit/8c56569398d766c1bbcb759d537e68cf2a330646

**Comment by donghd** [comment]
Hi @dpr-odoo ,
Thanks you for fixing. It seem work when login to Odoo 10 with correct user/pass.
However, if login to Odoo 10 (community version) with wrong user/pass, exception still happening. Can you check again?
```
OdooResponse{jsonrpc='null', error='null', id=null, result={error={message=Odoo Server Error, code=200.0, data={debug=Traceback (most recent call last):
  File "/opt/odoo_v10/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo_v10/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo_v10/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo_v10/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo_v10/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo_v10/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo_v10/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo_v10/addons/web/controllers/main.py", line 719, in authenticate
    return request.env['ir.http'].session_info()
  File "/opt/odoo_v10/addons/report/models/ir_http.py", line 11, in session_info
    res = super(IrHttp, self).session_info()
  File "/opt/odoo_v10/addons/web_tour/models/ir_http.py", line 12, in session_info
    result = super(Http, self).session_info()
  File "/opt/odoo_v10/addons/web/models/ir_http.py", line 29, in session_info
    "is_superuser": request.env.user._is_superuser(),
  File "/opt/odoo_v10/odoo/addons/base/res/res_users.py", line 575, in _is_superuser
    self.ensure_one()
  File "/opt/odoo_v10/odoo/models.py", line 4789, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.users()
, exception_type=internal_error, message=Expected singleton: res.users(), name=exceptions.ValueError, arguments=[Expected singleton: res.users()]}}, id=7657.0, jsonrpc=2.0}}
```

**Comment by mrgoetz** [comment]
Hi @dpr-odoo , thanks for you quick responses on that issue.
since we have a self hosted url, we are interested in the issue described in the title.
The workaround of @darfat works perfectly, but the question is, if there were side effects if we set the main company in every session object. Of course in this workaround we can first try to determine the proper company for that user and use main company as default. I will try that later.
What was the reason to presume that we have a company_id in the response in Version 8 ?
Perhaps we missed some upstream change sets, I will be looking for it. As far as I can see we do not need a company_id there.
cheers
Michael Götz-Schneider

**Comment by dpr-odoo** [comment]
@mrgoetz 
Odoo 8.0 (``authenticate`` and ``get_session_info`` methods) already returns ``company_id`` in  https://github.com/odoo/odoo/blob/8.0/addons/web/controllers/main.py#L785  So no need to put it.

I'm fixing the bug, and update available soon.

**Comment by dpr-odoo** [comment]
Fixed.
